name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd c-api && cargo build --release
    - name: Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: cold_clear
        path: target/release/cold_clear.dll

  build-windows-x86:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: rustup target add i686-pc-windows-msvc
    - name: Build
      run: cd c-api && cargo build --release --target=i686-pc-windows-msvc
    - name: Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: cold_clear_x86
        path: target/i686-pc-windows-msvc/release/cold_clear.dll

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd c-api && cargo build --release
    - name: Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: cold_clear_linux
        path: target/release/libcold_clear.so

  build-linux-x86:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: rustup target add i686-unknown-linux-musl
    - name: Build
      run: cd c-api && cargo build --release --target=i686-unknown-linux-musl
    - name: Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: cold_clear_linux_x86
        path: target/i686-unknown-linux-musl/release/libcold_clear.so

  build-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download NDK
      run: |
        curl -LO https://dl.google.com/android/repository/android-ndk-r21-linux-x86_64.zip
        unzip android-ndk-r21-linux-x86_64.zip -d $GITHUB_WORKSPACE
    - name: Setup
      run: |
        cargo install cargo-ndk
        rustup target add aarch64-linux-android armv7-linux-androideabi
    - name: Build
      run: |
        export NDK_HOME="${GITHUB_WORKSPACE}/android-ndk-r21"
        cd c-api
        cargo ndk --platform 21 --target armv7-linux-androideabi build --release
        cargo ndk --platform 21 --target aarch64-linux-android build --release
    - name: Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: cold_clear_android_armv7
        path: target/armv7-linux-androideabi/release/libcold_clear.so
    - name: Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: cold_clear_android_aarch64
        path: target/aarch64-linux-android/release/libcold_clear.so
